apiVersion: v1
kind: Service
metadata:
  name: {{ template "sofa.fullname" . }}-prometheus
spec:
  selector:
    app: {{ template "sofa.fullname" . }}-prometheus
  ports:
  - protocol: TCP
    port: {{ .Values.prometheus.port }}
    targetPort: {{ .Values.prometheus.port }}
