apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config 
data:
  prometheus.yml: |
    scrape_configs:
    - job_name: 'lookout-client'
      scrape_interval: 5s
      static_configs:
      - targets: ['{{ template "sofa.fullname" . }}-rpcserver:{{ .Values.rpcserver.port }}', '{{ template "sofa.fullname" . }}-rpcclient:{{ .Values.rpcclient.port }}']
