apiVersion: v1
kind: Service
metadata:
  name: {{ template "sofa.fullname" . }}-rpcclient
spec:
  selector:
    app: {{ template "sofa.fullname" . }}-rpcclient
  ports:
  - protocol: TCP
    port: {{ .Values.rpcclient.rest_port }}
    targetPort: {{ .Values.rpcclient.rest_port }}
    name: web
  - protocol: TCP
    port: {{ .Values.rpcclient.prometheus_port }}
    targetPort: {{ .Values.rpcclient.prometheus_port }}
    name: prometheus
