{{- if .Values.ingress.enabled }}
{{- $serviceName := include "sofa.fullname" . -}}
{{- $servicePort := .Values.zipkin.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  name: {{ template "sofa.fullname" . }}-zipkin
  labels:
    app: {{ template "sofa.fullname" . }}-zipkin
spec:
  rules:
    {{- range $host := .Values.ingress.zipkin_hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}-zipkin
              servicePort: {{ $servicePort }}
    {{- end -}}
{{- end }}
