apiVersion: v1
kind: Service
metadata:
  name: {{ template "sofa.fullname" . }}-zipkin
spec:
  selector:
    app: {{ template "sofa.fullname" . }}-zipkin
  ports:
  - protocol: TCP
    port: {{ .Values.zipkin.port }}
    targetPort: {{ .Values.zipkin.port }}
