apiVersion: v1
kind: Service
metadata:
  name: {{ template "sofa.fullname" . }}-zk
spec:
  selector:
    app: {{ template "sofa.fullname" . }}-zk
  ports:
  - protocol: TCP
    port: {{ .Values.zk.port }}
    targetPort: {{ .Values.zk.port }}
